### PR TITLE
Adding OpenSYCL support for AMD GPUs

### PR DESCRIPTION
**Pull request by seanofthemillers**
Adding OpenSYCL support for AMD GPUs
Changes:
- Enabled AMD support using RDC+OpenSYCL
- Minor modifications to bandwidth-bound kernels to improve performance
- Adding GPU-aware-mpi option for communication

@svtcli These are some changes we discussed a while back that we made to improve performance on AMD GPUs using OpenSYCL. The changes can be roughly grouped as:
- Fixes for CMake for OpenSYCL build with ROCm
   - To get this working we are slightly tweaking the build process to support relocatable-device-code (RDC) to allow for source code and kernels to be defined in separate files.
- Tweaks to `parForUpdateDu` and `parForRK` to isolate bandwidth bound portions in separate kernels. This gives a notable speedup for both AMD and NVidia.
- Adding new MPI_Isend/MPI_Irecv option to `Domain::BCex`. This is only enabled for AMD GPUs, but *should* also work for NVidia GPUs. This was mainly done because at this time OpenMPI/OpenUCX tends to use host buffers for `MPI_Sendrecv_replace` (pretty big impact on performance).

Known issues:
- These changes will only support AMD with a GPU-aware-MPI install (or no MPI). 
- The cmake configure currently requires explicitly stating `--offload-arch=gfx9XX` for AMD GPUs. This seems to be a side effect of mixing RDC and OpenSYCL and I don't have a good workaround. I added a note to this end in the README.

Performance uplift:
The following table was run with MPI disabled for a problem of the size `Mx=My=Mz=384`. FOM is reported in millions of cell updates per second (MCUPS)
| Device | MCUPS (before) | MCUPS (after) | Speedup |
|---|---|---|---|
| A100 40GB | 112 | 140 | 1.25x |
| MI210 | 61 | 124 | 2x |

### CODE REVIEW

**Comment by svtcli** [comment]
Hi @seanofthemillers !
Thank you for the patches, they are very welcome. This is a short comment even before I look into it (although I ofc remember our previous discussion and agree to the points): typically we do not adopt pull requests on this repository, as it is out of sync with our internal dev repository (private). 
We will need to discuss internally what the best way to include your changes would be... this is the first time we face this issue. 
Other than that, no problem, we are very happy of your contribution!
News will follow as the rest of the team is back from summer vacation.
Cheers,

**Comment by seanofthemillers** [comment]
Hi @svtcli, Sounds good. I figured you had a separate repo and debated sending a tarball/patch vs a PR. You can feel free to grab the diff from this PR and close it. I just wanted to make sure you guys had a copy of what we discussed a while back.

**Comment by svtcli** [comment]
yep. Cool... we will postpone the decision to the first dev meeting in September, we'll leave it open until then. Thanks again!

**Comment by svtcli** [comment]
We have had a good look at the change, and manually selected some for our new release.
We rejected or rewrote some others. Also the code has changed significantly in the meantime, so we won't merge this request as it is, but should some of these ideas still be needed in future, we can discuss it further. Thanks again!

**Pull request closed without merging**
